apiVersion: apps/v1
kind: Deployment
metadata:
  name:  category-api
  namespace: default
  labels:
    app:  category-api
spec:
  selector:
    matchLabels:
      app: category-api
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  category-api
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  category-api
        image:  satishlakshmireddy/category-k8:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
          - containerPort: 8081
        

        
        