server:
  port: 8081

spring:
  application:
    name: CATEGORY-K8
  datasource:
     password: ${RDS_PASSWORD:root}
     url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DB_NAME:microservices}
     username: ${RDS_USERNAME:root}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  
  
